name: test-environment
channels:
  - conda-forge
dependencies:
  # required dependencies
  - packaging=20.0
  - python=3.7
  - pyyaml
  - cloudpickle=1.5.0 # this is in the min from distributed
  - partd=0.3.10
  - fsspec=0.6.0
  - toolz=0.8.2
  # optional dependencies pulled in by pip install dask[distributed]
  - pip
  - pip:
      # TODO: Replace this with distributed=2021.05.0 once it is out
      - git+https://github.com/dask/distributed
  # test dependencies
  - pre-commit
  - pytest
  - pytest-cov
  - pytest-rerunfailures
  - pytest-xdist
