name: test-environment
channels:
  - conda-forge
dependencies:
  # required dependencies
  - packaging=20.0
  - python=3.7
  - setuptools<60.0
  - pyyaml>=5.3.1
  - cloudpickle=1.1.1
  - partd=0.3.10
  - fsspec=0.6.0
  - toolz=0.8.2
  # test dependencies
  - pre-commit
  - pytest
  - pytest-cov
  - pytest-rerunfailures
  - pytest-xdist
